name: Super-Linter

on: push

jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - shell: bash
        run: | 
          echo "
          \"repo_id\":\"${{ github.repository_id }}\",
          \"repo_name\":\"${{ github.repository }}\"
          " > metadata.json
          ls
      - name: Create metadata.json
        uses: actions/upload-artifact@v3
        with:
          name: metadata
          path: metadata.json

      - name: Run Super-Linter
        uses: github/super-linter@v3
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
